export const GET_PRODUCTS ='GET_PRODUCTS';
export const LOAD_PRODUCTS='LOAD_PRODUCTS';
export const ADD_PRODUCTS ='ADD_PRODUCTS';
export const FAIL_PRODUCTS ='FAIL_PRODUCTS';
export const EDIT_PRODUCTS ='EDIT_PRODUCTS';
export const GET_ONE_PRODUCTS='GET_ONE_PRODUCTS';